# Header
menu:
  Games: /
  # Games: /categories/games/
  # About: /about/
  About: /PressKit-PINIX/en/
  Die Deep - PressKit: /PressKit-DieDeep/en
  Alina of the Arena - PressKit: /PressKit-Alina/en
  WannaSurvive - PressKit: /PressKit-WS/en/

# favicon
favicon: favicon.ico

# Logo Image Source
logo_src: /images/PINIX_ICONOnly.png

# Theme Main Subtitle
subtitle_main: Games

# Theme Secondary subtitle
susbtitle_secondary:

# Footer About Section
about_footer: /pressKit/

# Default post title
default_post_title: project

# Default post cover index page (Recommended)
default_cover_index: "https://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/pinixgames
facebook_url: https://www.facebook.com/pinixgames
# instagram_url: https://www.instagram.com/
# github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
patreon_url: https://www.patreon.com/pinix
email_url: mailto:maxwei@pinixgames.com
# rss_url: \#
